name: 'on-push-action'

on:
  push:
    branches:
      - master
      - prod

concurrency:
  group: ${{ github.ref_name }}


jobs:
  preparing:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.step-changes.outputs.changes }}
      test: ${{ steps.step-noname.outputs.test }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 2
      
      - id: step-noname
        run: echo "test=good" >> $GITHUB_OUTPUT
        
      - id: step-changes
        run: |
          changes="$(git diff HEAD~1 HEAD --name-only | grep -E ".yml$" | wc -l)"
          echo "changes=$changes" >> $GITHUB_OUTPUT
          
  integration:
    runs-on: ubuntu-latest
    needs: preparing
    steps:
      - id: echo
        run: |
          echo "changes=${{ needs.preparing.outputs.changes }}"
          echo "changes=${{ needs.preparing.outputs.test }}"
