name: 'on-push-action'

on:
  push:
    branches:
      - master
      - prod

concurrency:
  group: ${{ github.ref_name }}


jobs:
  preparing:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.step-changes.outputs.changes }}
      test: ${{ steps.step-noname.outputs.test }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 2
      
      - id: step-noname
        run: echo "test=good" >> $GITHUB_OUTPUT
        
      - id: step-changes
        run: git diff HEAD~1 HEAD --name-only | grep -E ".yml$" | wc -l  >> $GITHUB_OUTPUT


  # integration:
  #   runs-on: ubuntu-latest
  #   needs: preparing
  #   if: ${{ needs.preparing.outputs.skip == 0 }}
  #   with:
  #     ref: ${{ github.ref }}
  #     base_ref: ${{ github.ref_name }}

  # delivery:
  #   runs-on: ubuntu-latest
  #   needs: integration
  #   with:
  #     ref: ${{ github.ref }}
  #     ref_name: ${{ github.ref_name }}
  #     new_tag: '${{ github.ref_name }}-${{ github.run_number }}'

  # trigger-deploy:
  #   runs-on: ubuntu-latest
  #   needs: delivery
  #   with:
  #     ref: ${{ github.ref }}
  #     ref_name: ${{ github.ref_name }}
  #     new_tag: '${{ github.ref_name }}-${{ github.run_number }}'

  # trigger-deploy-only:
  #   runs-on: ubuntu-latest
  #   needs: preparing
  #   if: ${{ needs.preparing.outputs.skip == 0 }}
  #   with:
  #     ref: ${{ github.ref }}
  #     ref_name: ${{ github.ref_name }}
